### ISSUE TITLE
GradleException is not found

### ISSUE THREAD

**Issue by spDev002** [hypertrack/hypertrack-live-android#12]
Publishable Key is Missing in key.properties file.
Refer Step 2 at https://github.com/hypertrack/hypertrack-live-android#to-use-this-app for more info.
<a href="openFile:/home/spipl5/Downloads/hypertrack-live-android-master/app/build.gradle">Open File</a>

Error file : GradleException is not found in build.gradle

**Comment by amanjain08** [comment]
You need to add a Publishable Key in key.properties file.
Step 1: Sign up on [HyperTrack](https://dashboard.hypertrack.com/signup).
Step 2: Get and Copy [Publishable Key](https://docs.hypertrack.com/gettingstarted/pricing.html#get-a-test-authentication-keys)
Step 3: Paste Publishable Key at [key.properties](https://github.com/hypertrack/hypertrack-live-android/blob/master/key.properties) file.
