### ISSUE TITLE
Can't sign up on demo app

### ISSUE THREAD

**Issue by asadwaheed1** [hypertrack/hypertrack-live-android#13]
API gives this error createUser: 403: You do not have permission to access the resource. {"detail":"Invalid token."}. I have already applied my test production key in key.properties

**Comment by TheYsconator** [comment]
Heya! :) You've closed the issue, but forgot to mention how you've solved it. Can you explain how you solved this issue? I think I have a similar issue: public Hypertrack key added in two places, Google Maps key added, but still a 403.
