### ISSUE TITLE
Cannot create directory!! 

### ISSUE THREAD

**Issue by SusmithaRajuri** [hypertrack/hypertrack-live-android#14]
Error:Execution failed for task ':app:packageDebug'.
> Cannot create directory C:\Users\admin\Downloads\C1MP\hypertrack-live-android-master\app\build\outputs\apk\debug\C:\Users\admin\Downloads\C1MP\hypertrack-live-android-master\app\build\intermediates\instant-run-resources
![capture](https://user-images.githubusercontent.com/30102352/35215706-23c766bc-ff8b-11e7-8b18-cdbab154d9c6.PNG)

**Comment by Rissmon** [comment]
I have added below code:

android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "${variant.name}-${variant.versionName}.apk"
    }
}

Now the issue is fixed
