### ISSUE TITLE
Hypertrack Notification and Stop Running Location Sharing

### ISSUE THREAD

**Issue by dgaurav-163** [hypertrack/hypertrack-live-android#15]
Hi Hypertrack Team

I am using hypertrack sdk in my app for location sharing. I want to know how we can customize notification icon which is show in app notification bar. 

I want to also know, suppose if i am sharing my location to other people and when i stop sharing from other user end so how i can know status of running sharing. on the basis of i have to disable/remove notification icon.

Please suggest me solution for this

Thanks
Gaurav

**Comment by amanjain08** [comment]
Hey @dgaurav-163 
1. Notification that shows up in the notification bar is completely customizable. Follow this link for customization https://docs.hypertrack.com/sdks/android/troubleshoot.html#customizing-notification-advanced

2. I didn't understand your second question properly. Can you please tell us in a bit more detail?

**Comment by dgaurav-163** [comment]
Hi Aman Thanks for your respond. 

Now I am able to set custom icon and message but it's showing in light gray color. How Can I make it black color or change color?

For Point 2 - Let us suppose I am sharing my location with two users. At the location sharing time I show notification message in notification bar. 
My Question is how we can recognise location sharing is running or it's stop from all user end?
(New Points)
Point3 - Can we share location as time based? Suppose I have to share my location for 2 hours.

Thanks
Gaurav

**Comment by amanjain08** [comment]
1. You can't the change background color of notification. But you can set a view to the notification in which you can make do any customization.

2. As of now, when the app is in the background there is no way to determine that other people have stopped sharing his location. You need to maintain this state on your server and communicate to the app using FCM.

3. You can set up an alarm to stop sharing location, currently, SDK doesn't have this as an inbuilt feature.

**Comment by dgaurav-163** [comment]
Thanks Aman for your response!
