### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by md0092651** [hypertrack/hypertrack-live-android#5]
when you come to foreground by clicking on the notification and your location service is disable you are asked to enable the gps. if you click on the cancel button the app crashes every time. 

device: moto g3
OS : 6.0.1

**Comment by amanjain08** [comment]
@md0092651  Thanks for pointing this out. We have fixed the issue in this [commit]((https://github.com/hypertrack/hypertrack-live-android/commit/8ef8818a62051d1ccede6cb9aa01dbdae51f861a)).
