### ISSUE TITLE
Unable to run this app in my Android Studio 

### ISSUE THREAD

**Issue by anuragsidana** [hypertrack/hypertrack-live-android#8]
I followed step by step the procedure given in the readme but every time I try building the project, I get this error-:
**Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.
 Crashlytics Developer Tools error.**
Please help me out !!!
Curious to contribute to this project ;-)

**Comment by ivarjain** [comment]
Hi Anurag, 
You need to add the Crashlytics API Key in the android manifest. We use crashlytics for our crash reporting. You can get one by signing up on Fabric : https://fabric.io/kits/android/crashlytics

<application>
    <meta-data
        android:name="com.crashlytics.ApiKey"
        android:value="your key here" />
</application>

We will remove the crashlytics dependency after checking with the team. Hope it helps.

**Comment by anuragsidana** [comment]
Hello @ivarjain 
Tried with your solution and added the api key . Still getting the same error .

**Comment by amanjain08** [comment]
Hey Anurag,

Sorry for the trouble. I am updating the repo with the fix.

Thanks & Regards,

*Aman Jain*

**Comment by amanjain08** [comment]
@anuragsidana Released the [fix](https://github.com/hypertrack/hypertrack-live-android/commit/3115efa9e59e96654fb7ea2c2cca6bc8a66e5905#diff-39e7d8c00954e920b98e7636f0ac30b2R138) for fabric crashlytics issue.
